// Copyright Istio Authors
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: stability/level.proto

package stability

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Level defines the stability levels Istio uses.
type Level int32

const (
	Level_EXPERIMENTAL Level = 0
	Level_ALPHA        Level = 1
	Level_BETA         Level = 2
	Level_STABLE       Level = 3
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "EXPERIMENTAL",
		1: "ALPHA",
		2: "BETA",
		3: "STABLE",
	}
	Level_value = map[string]int32{
		"EXPERIMENTAL": 0,
		"ALPHA":        1,
		"BETA":         2,
		"STABLE":       3,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_stability_level_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_stability_level_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_stability_level_proto_rawDescGZIP(), []int{0}
}

var File_stability_level_proto protoreflect.FileDescriptor

var file_stability_level_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2e, 0x73,
	0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2a, 0x3a, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x58, 0x50, 0x45, 0x52, 0x49, 0x4d, 0x45, 0x4e, 0x54, 0x41,
	0x4c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x4c, 0x50, 0x48, 0x41, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x42, 0x45, 0x54, 0x41, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x42,
	0x4c, 0x45, 0x10, 0x03, 0x42, 0x18, 0x5a, 0x16, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2e, 0x69, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stability_level_proto_rawDescOnce sync.Once
	file_stability_level_proto_rawDescData = file_stability_level_proto_rawDesc
)

func file_stability_level_proto_rawDescGZIP() []byte {
	file_stability_level_proto_rawDescOnce.Do(func() {
		file_stability_level_proto_rawDescData = protoimpl.X.CompressGZIP(file_stability_level_proto_rawDescData)
	})
	return file_stability_level_proto_rawDescData
}

var file_stability_level_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stability_level_proto_goTypes = []interface{}{
	(Level)(0), // 0: istio.stability.Level
}
var file_stability_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stability_level_proto_init() }
func file_stability_level_proto_init() {
	if File_stability_level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stability_level_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stability_level_proto_goTypes,
		DependencyIndexes: file_stability_level_proto_depIdxs,
		EnumInfos:         file_stability_level_proto_enumTypes,
	}.Build()
	File_stability_level_proto = out.File
	file_stability_level_proto_rawDesc = nil
	file_stability_level_proto_goTypes = nil
	file_stability_level_proto_depIdxs = nil
}
